#--- CONFIGURACIÓN DEL SISTEMA TÁCTICO SARGO ---
#Fri Mar 13 08:33:24 ART 2026
ruta_mapa_defecto=C\:/Users/54293/Desktop/Archivos SARGO/mapaV1.TIF
ip_sugerida_UI=192.168.0.
puerto_enlace=10011
ips_destinos=192.168.1.2,192.168.2.2
operadores_autorizados=admin,juarez
prefijo_blancos=AF
contador_blancos_inicio=6400
